
 let moviesArr={ moviesArr: [ 
	{"name":"cinema name", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	"code":1, 
	"url":"http://via.placeholder.com/250x360", 
  }, 
	{"name":"cinema name", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	"code":1, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	"code":1, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	"code":1, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	"code":1, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"cinema name", 
	"code":1, 
	"url":"http://via.placeholder.com/250x360", 
  }
]
}
export default moviesArr;