
 let films_soonArr={ films_soonArr: [ 
	{"name":"Movie title", 
	  "code":1, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	"code":2, 
	"url":"http://via.placeholder.com/250x360", 
  }, 
	{"name":"Movie title", 
	  "code":3, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	"code":4, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	  "code":5, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	"code":6, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	  "code":7, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	"code":8, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	  "code":9, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	"code":10, 
	"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	  "code":11, 
		"url":"http://via.placeholder.com/250x360", 
	}, 
	{"name":"Movie title", 
	"code":12, 
	"url":"http://via.placeholder.com/250x360", 
  }
]
}
export default films_soonArr;